# Generated by Django 4.1.2 on 2023-02-04 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Resume", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="achievements",
            field=models.TextField(default="", max_length=1000),
        ),
        migrations.AddField(
            model_name="profile",
            name="trainings_courses",
            field=models.TextField(default="", max_length=1000),
        ),
    ]
